package de.leonseeger.scotlandyardinreallife.ui.components

import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.LocalLifecycleOwner
import  android.content.Context
import de.leonseeger.scotlandyardinreallife.BuildConfig
import org.maplibre.android.camera.CameraPosition
import org.maplibre.android.geometry.LatLng
import org.maplibre.android.maps.MapLibreMapOptions
import org.maplibre.android.maps.MapView

@Composable
fun CustomMap(modifier: Modifier, styleUrl: String, lat: Double, lon: Double, appContext: Context){
    val mapOptions = MapLibreMapOptions.createFromAttributes(appContext)
    mapOptions.apply {
        apiBaseUri(BuildConfig.MAPTILER_API_PATH)
        camera(
            CameraPosition.Builder()
                .bearing(0.0)
                .target(LatLng(lat,lon))
                .zoom(3.9)
                .build()
        )
        maxZoomPreference(26.0)
        minZoomPreference(2.0)
        zoomGesturesEnabled(true)
        scrollGesturesEnabled(true)
        rotateGesturesEnabled(true)
        compassEnabled(true)
        tiltGesturesEnabled(false)
    }
    val mapView = MapView(appContext, mapOptions)

    AndroidView(
        modifier = modifier,
        factory = { mapView }) { view ->
                view.getMapAsync { map ->
                    map.setStyle(styleUrl)
                }
            }
}

/*
@Composable
fun rememberMapViewWithLifecycle(): MapView { //saves resources. generated by chatgpt
    val context = LocalContext.current
    val mapView = remember { MapView(context) }

    val lifecycle = LocalLifecycleOwner.current.lifecycle

    DisposableEffect(lifecycle) {
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_CREATE -> mapView.onCreate(null)
                Lifecycle.Event.ON_START -> mapView.onStart()
                Lifecycle.Event.ON_RESUME -> mapView.onResume()
                Lifecycle.Event.ON_PAUSE -> mapView.onPause()
                Lifecycle.Event.ON_STOP -> mapView.onStop()
                Lifecycle.Event.ON_DESTROY -> mapView.onDestroy()
                else -> Unit
            }
        }

        lifecycle.addObserver(observer)
        onDispose {
            lifecycle.removeObserver(observer)
        }
    }

    return mapView
}*/
