# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
      app: "1:507791721804:android:1209770383c12ce846bbe9", 
      groups: "testers",
      release_notes: "Beta build from fastlane"
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end